### ISSUE TITLE
Improvement: issue a schema warning when encountering unknown fields in a package's SDF

### ISSUE THREAD

**Issue by cjdcordeiro** [canonical/chisel#176]
Today, Chisel is permissive and ignores unknown YAML fields from a Slice Definitions File.

This may cause new slice definitions to have typos that go unnoticed. For example:
 - in https://github.com/canonical/chisel-releases/actions/runs/12000988007/job/33450865802, the daily installation jobs started failing after https://github.com/canonical/chisel/pull/170 was merged. The error gave the wrong impression that the copyright files were missing and that such an error was driven by https://github.com/canonical/chisel/pull/170. In reality, the error came from the fact that the corresponding SDF had the top-level field `esential` instead of `essential`.

## UX improvement suggestion

The existing schema in https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/chisel-slices.json is manually maintained. Until a more dynamic and automated solution is put in place to rely on this repo as the source of truth for the SDF's and `chisel.yaml` schemas, a simple improvement would be to _let Chisel throw a simple warning in these cases: e.g. `WARNING: Ignoring unknown field 'esential' in libfoo.yaml`_.

**Comment by lorenzo-medici** [comment]
Hi. I would like to try and take care of this issue!

**Comment by lorenzo-medici** [comment]
After some investigation into the issue, I found a potential solution:
In `internal/setup/yaml.go` the `yaml.Decoder` responsible for reading the yaml files is configured with `dec.KnownFields(false)`, meaning that it does not check that all the fields in the input data map to an existing field in the defined go structure.

A fix for this issue could be switching the two occurrences of this setup call to a `true` value.
The first is responsible for checking Releases, while the second is responsible for checking packages.

I have tested locally with the cloned `chisel-releases` repository and manually modifying the files. For example, modifying `chisel.yaml` or a file for a random library (in this case `slices/libkmod2.yaml`).
The command used from now on is `chisel cut --release chisel-releases/ --root myrootfs/ libkmod2_libs`, and the `KnownFields` option is active.

When the files are not modified the execution proceeds as normal.
Changing the name of an existing field (archives -> archive) in `chisel.yaml` results in:
```
2024/11/27 17:44:08 Processing chisel-releases/ release...
error: chisel.yaml: cannot parse release definition: yaml: unmarshal errors:
  line 3: field archive not found in type setup.yamlRelease
```
which is caught by changing the option to `true` in the `parseRelease` function.

Adding a new field `test: aaa` to the file results in 
```
2024/11/27 17:45:40 Processing chisel-releases/ release...
error: chisel.yaml: cannot parse release definition: yaml: unmarshal errors:
  line 46: field test not found in type setup.yamlRelease
```
and with both changes
```
2024/11/27 17:46:18 Processing chisel-releases/ release...
error: chisel.yaml: cannot parse release definition: yaml: unmarshal errors:
  line 3: field archive not found in type setup.yamlRelease
  line 46: field test not found in type setup.yamlRelease
```
This also works for substanza parameters (e.g. `archives.ubuntu.version` -> `version-new`) yields
```
2024/11/27 17:46:52 Processing chisel-releases/ release...
error: chisel.yaml: cannot parse release definition: yaml: unmarshal errors:
  line 6: field version-new not found in type setup.yamlArchive
```

Performing similar operations on individual slice files results in 
```
2024/11/27 17:48:38 Processing chisel-releases/ release...
error: cannot parse package "libkmod2" slice definitions: yaml: unmarshal errors:
  line 3: field esential not found in type setup.yamlPackage
```
and
```
2024/11/27 17:49:03 Processing chisel-releases/ release...
error: cannot parse package "libkmod2" slice definitions: yaml: unmarshal errors:
  line 3: field esential not found in type setup.yamlPackage
  line 19: field test not found in type setup.yamlPackage
```
which are caught by changing the option to true in `parsePackage`


This opens two questions:
1. the issue mentions a warning while this solution produces a terminating error. Introducing a waning would increase the complexity of the solution requiring 1. setting `KnownFields` as ~false and 2. recursively checking if all fields of the input file have a correspondence in the created structure. Which way should be picked? 
2. I am not sure how I could produce tests for this functionality, the tests I found in the repository all use the release repository. Should I create a new test action (or modify the simple one) to download a subset of the release repository, programmatically change some keys and check that the errors are thrown?

The proposed patch for the fix is [attached](https://github.com/user-attachments/files/17937054/proposed.patch.txt)

**Comment by cjdcordeiro** [comment]
Hi @lorenzo-medici 

I truly appreciate your take on this! That's exemplary!

I believe we may have a new suggestion that invalidates the need to address this issue -> https://github.com/canonical/chisel/issues/178

I'm closing this issue with the rationale that while "warnings" may be a desired future feature, their implementation as a solution for the aforementioned problem is sub-optimal, because:
 1. a warning is not an error and thus it wouldn't enforce any validation of the schema
 2. one (e.g. our CI) would need to actually run `chisel` in order to validate the schema, which is unnecessarily expensive
 3. the warnings don't provide the best feedback to contributors who are writing new slices, since you'll want to know that you have a schema issue (and why) at the time of writing the definitions.

Thank you again for your contribution nonetheless!
