### ISSUE TITLE
Chisel image not available in docker hub

### ISSUE THREAD

**Issue by luispabon** [canonical/chisel#46]
```
~ docker pull chisel:22.04
Error response from daemon: pull access denied for chisel, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
 ```

**Comment by valentincanonical** [comment]
Hey there! I realised reading this issue that the confusion might come from my blog on https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless (as I'm referring to a `chisel:22.04` image there). Is that the case? 
If so, as described in the "Step 1" section, you are required to build and tag the "chisel" image locally in case you want to follow the following instructions.

**Comment by luispabon** [comment]
Thank you, I believe I might have missed that.

I'm a bit stumped on how to actually use this though, for instance:

```
RUN ["chisel", "cut", "--root", "/staging", \
   "base-files_base", \
   "base-files_release-info", \
   "ca-certificates_data", \
   "libc6_libs", \
   "libssl3_libs", \
   "openssl_config" ]
```

All those values there, where do they come from? Is there any actual docs (other than your introductory blog post) on how to use the chisel tool?

**Comment by valentincanonical** [comment]
I have to say we have been more focused on delivering useful chiselled Ubuntu images and evolving the tool than documenting it, our bad here! You can expect more stability and docs in the next months. 

In the meantime, we have some documentation for Chisel there: https://canonical-rockcraft.readthedocs-hosted.com/en/latest/how-to/install-slice.html. The reason it's part of the "Rockcraft" documentation currently is because we are building Chisel at first in order to support this other building tool that will offer a declarative framework to build and keep track of OCI images.

The shared documentation link should answer your specific questions.

**Comment by luispabon** [comment]
Grand, thank you for your help @valentincanonical 👍

**Comment by polarathene** [comment]
FWIW it was a bit odd to see this on the article:

```Dockerfile
RUN ["chisel", "cut", "--root", "/staging", \
   "base-files_base", \
   "base-files_release-info", \
   "ca-certificates_data", \
   "libc6_libs", \
   "libssl3_libs", \
   "openssl_config" ]
```

You'd normally just use:

```Dockerfile
RUN chisel cut --root /staging \
   base-files_base \
   base-files_release-info \
   ca-certificates_data \
   libc6_libs \
   libssl3_libs \
   openssl_config
```

---

Several of the chisel resources promoting it do talk about a minimal image equivalent to Google's debian distroless offerings for projects like Rust and Go to leverage, but this doesn't seem to exist at a registry like the published rocks for other services or language runtimes. I'll raise a separate issue about that.
