### ISSUE TITLE
Master thesis on container security

### ISSUE THREAD

**Issue by mwager** [canonical/chisel#88]
Hi everyone,

I am currently starting to write my master thesis on evaluating the security of software containers through reduction of potentially vulnerable components. Of course chisel should be part of it 😊

I am working as part of a product security team in a large enterprise and our scanners mostly find a lot. That's why we went deep into distroless and currently recommending it in order to reduce findings. In literature I read a lot that this will reduce the attack surface. Nevertheless in the evening I am wrapping my head around the question if this really leads to more secure images. Lots of scanner findings are not exploitable in the context of certain apps anyway, I suppose.

Currently I am doing some research on related work, and I found 2 very interesting papers (2022)

- https://ieeexplore.ieee.org/abstract/document/9911523
- https://ieeexplore.ieee.org/document/9825857

The first one is a comprehensive comparison of distroless vulnerability findings vs. other base images. I guess in my thesis I could extend this to also include chiseled images...
Second one is a Study of Exploitability & Impact of Base-Image Vulnerabilities"

The goal should be e.g. to make better statements on accepting risks(scanner findings)

Soon I will dive as deep as I can into the codebase here :)

**Are there already any kind of "pre built" runtime images? Like java, node.js, python etc? I saw smt about .NET..**

**And is there any communications channel like slack/google group etc?**

Appreciate any input 😊 and sorry for the spam here, could not find another discussion group...

Kind regards
Michael

**Comment by valentincanonical** [comment]
Hi Michael,

Thanks for reaching out and showing interest in featuring Chisel into your master's thesis! It's nice and truly rewarding to see that the work we're doing is sparking academic interest and contributing to further research on the security of software containers. 😊

To address your points:

- It's true that not all scanner findings are exploitable, especially in the context of specific applications. However smaller container images like the ones created using Chisel effectively minimise the number of components that could potentially have vulnerabilities or get used in an attack strategy (eg, no package manager, no shell). Even if these vulnerabilities are not always exploitable, this reduction inherently makes the container safer. The fact that Chisel operates at the file-level (and not the typical package-level) should make this even more beneficial, since vulnerabilities might not affect the entirety of a package. 

- Regarding the studies you've found, these seem like very relevant resources. Extending the comparison to include Chiseled images in your thesis would provide a new perspective and valuable insights for the community. More than happy to support you with anything you might need! Also, looking forward to reading your paper (assuming you'll make it a public ressource? 😉).

- We do have pre-built runtime images for various languages. As of now, we have package slices support for C/C++, Go, Rust, .NET, and Java applications with prebuilt chiselled images. More toolchains are coming. We'd like to spread the message that the best base image is "from scratch" and promote the use of "chisel" in multi-stage builds to only pull exactly the needed dependencies for each container image. However, we do have toolchain-specific prebuilt images to showcase chiselled Ubuntu and provide an easy way to get started. See mainly https://hub.docker.com/r/ubuntu/dotnet-deps, https://hub.docker.com/r/ubuntu/dotnet-runtime, https://hub.docker.com/r/ubuntu/jre. Also, read more about using Chisel to build your custom chiselled Ubuntu base image: https://canonical-public-cloud.readthedocs-hosted.com/en/latest/oci/oci-how-to/create-chiselled-ubuntu-image.html. (https://ubuntu.com/blog/craft-custom-chiselled-ubuntu-distroless)

As for communication channels, we are currently using Github for discussions around Chisel. There's a more generic Discourse topic around what Canonical is doing related to container images: https://discourse.ubuntu.com/c/rocks/117, feel free to open a thread there! Otherwise, if you'd like a more direct channel, you can talk to us on Mattermost (most relevant channel would be https://chat.charmhub.io/charmhub/channels/rockcraft) or email the team at rocks@canonical.com.

Additionally, we would be delighted to get your feedback and findings as you dive into our codebase and begin working with Chisel. We'd love to improve Chisel and its use in creating more secure container images!

Best of luck with your master's thesis, looking forward to your contributions!

**Comment by mwager** [comment]
Hey Valentin, 

thank you for your quick answer!

Yeah I will probably publish it, will let you know 😊 Should be around November :) 

Thx for the info on pre-built runtime images, the resources and everything!

**Comment by mwager** [comment]
Hey Valentin,

I finished the thesis and made a paper out of it, if you are interested, here is the link: 

https://mwager.de/assets/component_reduction_paper.pdf

**Comment by rebornplusplus** [comment]
This is great!!

(ping @ValentinViennot)
