### ISSUE TITLE
Can we get an apt package for chisel?

### ISSUE THREAD

**Issue by rarera** [canonical/chisel#89]
currently there are no installers for chisel it would be nice if this would be available using apt.

**Comment by cjdcordeiro** [comment]
Hi @rarera

Thanks for reaching out. Although it might happen in the future, we currently have no **immediate** plans to create a deb for Chisel. 

We will, very soon, have GitHub releases though. So that will make the installation of the Chisel binary much simpler ;) 

I hope this is good enough for the time being. I'm closing the issue but if there is a very compelling use case where a deb would be required, please re-open it and share the use case with us.
